name: dev-cd-wf

on:
  push:
    branches:
      - develop

jobs:
  dev-deploy-job:
    runs-on: ubuntu-latest
    environment: "University-notice-board"
    steps:
      - name: Deploy Develop Branch Code on Render 
        run: curl -x POST ${{secrets.RENDER_DEVELOP_DEP}}