name: ci-wf

on:
  push:
    branches:
      - feature/notices
  pull_request:
    branches:
      - feature/notices

jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Lint Dependencies
        run: npm install --save-dev htmlhint stylelint parcel

      - name: Lint HTML
        run: npx htmlhint "src/*/.html"

      - name: Lint CSS
        run: npx stylelint "styles/*/.css"

  build-job:
    runs-on: ubuntu-latest
    needs: lint-job
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Parcel
        run: npm install --save-dev parcel

      - name: Build Website
        run: npx parcel build "./src/index.html" --dist-dir "dist" --public-url "./" --no-cache

  docker-push-job:
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/uni-notice-board:latest_v2 .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/uni-notice-board:latest_v2