name: ci-wf

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome step
        run: echo "Starting Linting Job for Assignment 3"
      - name: Clone Repository
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install --save-dev htmlhint stylelint parcel
      - name: Lint HTML Files
        run: npx htmlhint "src/**/*.html"
      - name: Lint CSS Files
        run: npx stylelint "styles/**/*.css"

build-job:
  runs-on: ubuntu-latest
  needs: lint-job
  steps:
    - name: Welcome to Build Job
      run: echo "Linting passed! Starting Parcel Build and Docker"

    - name: Clone Repository
      uses: actions/checkout@v6

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm install --save-dev parcel

    - name: Build Website with Parcel
      run: npx parcel build "./src/index.html" --dist-dir "dist" --public-url "./" --no-cache

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/uni-notice-board:latest .

    - name: Push Docker Image to Docker Hub
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/uni-notice-board:latest

    - name: Optional: Test Run Docker Container
      run: |
        docker container run -d -p 8080:80 ${{ secrets.DOCKER_HUB_USERNAME }}/uni-notice-board:latest
        docker container ls